name: RuboCop Linter
on: [push]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'

      - name: Install dependencies
        run: bundle install

      - name: Run RuboCop
        run: bundle exec rubocop
