name: RSpec Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.1'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install SQLite
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3 libsqlite3-dev

      - name: Install dependencies
        run: bundle install

      - name: Install JS dependencies
        run: yarn install --check-files

      - name: Setup database
        run: bin/rails db:setup

      - name: Run tests
        run: bundle exec rspec
